name: Build

on: [push]

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install setuptools and wheel first
      run: pip3 install setuptools wheel

    - name: Install XVFB (Ubuntu only)
      run: sudo apt-get install -y xvfb
      if: ${{ matrix.os == 'ubuntu-latest' }}

    - name: Install XVFB (macOS only)
      run: |
          brew install --cask xquartz
          echo "/usr/X11/bin" >> $GITHUB_PATH
      if: ${{ matrix.os == 'macos-latest' }}

    - name: Install dependencies (Python) (Ubuntu and macOS only)
      run: make update
      if: ${{ matrix.os != 'windows-latest' }}

    - name: Install dependencies (Python) (Windows only)
      run: make update CFLAGS=--user
      if: ${{ matrix.os == 'windows-latest' }}

    - name: Install dependencies (JS)
      run: npm install

    - name: Lint
      run: make lint radon

    - name: Test
      run: make test test_system

    - name: Docs
      run: make docs

    - name: Build package
      run: make build

    # - name: Push the docs
    #   uses: cpina/github-action-push-to-another-repository@master
    #   env:
    #     API_TOKEN_GITHUB: ${{ secrets.DOCS_API_TOKEN_GITHUB }}
    #   with:
    #     source-directory: 'docs/build'
    #     destination-github-username: ${{ secrets.DOCS_USERNAME_GITHUB }}
    #     destination-repository-name: 'webtraversallibrary-docs'
    #     user-email: ${{ secrets.DOCS_EMAIL_GITHUB }}
